from django.db import models


class PlayerCharacters(models.Model):
    process_uuid = models.CharField('UUID', max_length=50, default=None)
    generation = models.IntegerField('世代')
    board_scores = models.CharField('カンマ区切りスコア', max_length=50, db_index=True)
    score01 = models.SmallIntegerField()
    score02 = models.SmallIntegerField()
    score03 = models.SmallIntegerField()
    score04 = models.SmallIntegerField()
    score05 = models.SmallIntegerField()
    score06 = models.SmallIntegerField()
    score07 = models.SmallIntegerField()
    score08 = models.SmallIntegerField()
    score09 = models.SmallIntegerField()
    score10 = models.SmallIntegerField()
    board_score_black = models.TextField('黒のスコアインデックスを計算したJSON', default=None, null=True)
    board_score_white = models.TextField('白のスコアインデックスを計算したJSON', default=None, null=True)
    weight1 = models.SmallIntegerField()
    weight2 = models.SmallIntegerField()
    weight3 = models.SmallIntegerField()
    match_count = models.IntegerField('試合数', default=0)
    win_count = models.IntegerField('勝ち数', default=0)
    lose_count = models.IntegerField('負け数', default=0)
    total_stone = models.IntegerField('試合終了時の石の数の合計', default=0)
    is_last_gen = models.BooleanField('最後の世代かどうか', default=False)
